In [36]:
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.preprocessing import StandardScaler

In [37]:
from sklearn.model_selection import train_test_split
import sklearn.metrics

In [38]:
from sklearn.metrics import accuracy_score, classification_report, recall_score

In [39]:
df = pd.read_csv('/Users/aslihankoksoy/Downloads/diabetes.csv')

In [40]:
print(df.shape)

(768, 9)


In [41]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [42]:
X= df.iloc[:,:8]

In [43]:
y = df['Outcome']

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=0)

In [45]:
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(576, 8) (576,) (192, 8) (192,)


# Normalizing

In [46]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_train[:5,:]

array([[ 1.50755225, -1.01521454, -0.40451932, -1.31921491, -0.71823753,
        -1.22070104, -0.98325882, -0.04863985],
       [-0.82986389, -0.09964691, -0.61509602,  0.9287299 ,  0.08374747,
         0.13719053, -0.62493647, -0.88246592],
       [-1.12204091, -0.95207195,  0.54307587, -1.31921491, -0.71823753,
         0.0240329 ,  0.39884168, -0.5489355 ],
       [ 2.38408331,  0.59492164,  0.64836422,  1.36583027,  2.05458297,
         0.87900167,  0.17903049,  2.03592532],
       [ 1.50755225,  0.75277813,  0.54307587,  1.55315901,  0.39089067,
         0.71555175,  0.50724171,  0.53503839]])

# creating Support Vector Machine

In [47]:
csvm = svm.SVC(kernel='sigmoid')
csvm.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='sigmoid',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

#Boundaries

In [48]:
y_pred = csvm.predict(X_train)
print(y_pred)

[0 0 0 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0
 0 1 1 0 0 1 0 0 0 0 1 1 1 0 0 0 1 0 1 1 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 0
 1 1 0 0 1 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 0
 0 1 1 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 0 1 1 1 1 0 0 0 0 0 0 0
 1 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 1 1 1 0 1 1 1 0 0 1 1 0 0 0 0 1 1
 0 0 1 1 0 0 1 1 1 1 0 1 0 0 0 1 0 1 1 0 0 1 0 1 0 0 1 1 0 0 0 0 0 0 1 0 1
 0 0 0 1 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1 1 0 1 0 0 1 0 1 1 0 0 1 0 0 0 1 1
 0 0 1 0 0 1 1 1 1 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 0 0 1 0 0 1 1 1 0 0 1 1 1
 0 1 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0
 0 1 0 1 0 0 0 0 0 0 1 0 0 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0
 0 1 0 1 0 0 0 1 0 1 0 1 0 0 0 1 0 1 0 0 0 1 1 0 0 0 0 0 0 1 0 1 1 0 0 0 0
 1 1 0 0 0 1 1 1 0 1 0 1 0 1 0 0 0 1 1 1 0 1 0 1 0 0 0 1 1 0 0 1 0 1 1 0 0
 0 0 1 0 0 0 0 0 0 0 1 0 1 1 1 1 0 0 1 1 1 1 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0
 1 0 1 0 1 0 1 0 0 1 0 0 

In [49]:
print(accuracy_score(y_train, y_pred))

0.6510416666666666


## trying kernels

In [50]:
for k in ('linear', 'poly', 'rbf', 'sigmoid'):
    csvm = svm.SVC(kernel=k)
    csvm.fit(X_train, y_train)
    y_pred = csvm.predict(X_train)
    print(k)
    print(accuracy_score(y_train, y_pred))

linear
0.7638888888888888
poly
0.7934027777777778
rbf
0.8246527777777778
sigmoid
0.6510416666666666


In [51]:
for k in ('linear', 'poly', 'rbf', 'sigmoid'):
    csvm = svm.SVC(kernel=k)
    csvm.fit(X_train, y_train)
    y_pred = csvm.predict(X_train)
    print(k)
    print(recall_score(y_train, y_pred))

linear
0.5631067961165048
poly
0.470873786407767
rbf
0.6456310679611651
sigmoid
0.5


In [52]:
csvm = svm.SVC(kernel='rbf')
csvm.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

## hypothetical patient

In [53]:
#Pregnancies	Glucose	BloodPressure	SkinThickness	Insulin	BMI	DiabetesPedigreeFunction	Age
patient = np.array([[ 1., 200., 75., 40., 0., 45., 1.5, 20]])
patient = scaler.transform(patient)
csvm.predict(patient)

array([1])

#change glucose to lower and rerun 

In [54]:
#Pregnancies	Glucose	BloodPressure	SkinThickness	Insulin	BMI	DiabetesPedigreeFunction	Age
patient = np.array([[ 1., 50., 75., 40., 0., 45., 1.5, 20]])
patient = scaler.transform(patient)
csvm.predict(patient)

array([0])

## real patients one by one test

In [55]:
patient = np.array([X_test.iloc[0]])
patient = scaler.transform(patient)
print(csvm.predict(patient))
print( y_test.iloc[0])

[1]
1


In [56]:
patient = np.array([X_test.iloc[2]])
patient = scaler.transform(patient)
print(csvm.predict(patient))
print( y_test.iloc[2])

[0]
0


In [57]:
patient = np.array([X_test.iloc[9]])
patient = scaler.transform(patient)
print(csvm.predict(patient))
print( y_test.iloc[9])

[0]
0


## Accuracy of the SVM classifier on the whole dataset (test subj)

In [58]:
X_test = scaler.transform(X_test)
y_pred = csvm.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.7760416666666666


## comparison to all-zero prediction

In [59]:
y_zero =  np.zeros(y_test.shape)
print(accuracy_score(y_test, y_zero))

0.6770833333333334


## Precision and Recall

In [60]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      0.90      0.84       130
           1       0.71      0.52      0.60        62

    accuracy                           0.78       192
   macro avg       0.75      0.71      0.72       192
weighted avg       0.77      0.78      0.77       192

